apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kanboard.fullname" . }}
  labels:
    app: {{ template "kanboard.name" . }}
    chart: {{ template "kanboard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- with .Values.database.url }}
  database-url: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.apiAuthenticationToken }}
  api-authentication-token: {{ . | b64enc | quote }}
  {{- end }}
